language: python
dist: xenial
python:
  - "3.8"
# command to install dependencies
install:
  - pipenv sync
  - pip install -e .
# command to run tests
script:
  - pytest
  - flake8 
after_success:
  - coveralls
